    @startuml
title
商品入荷登録画面の状態遷移
end title
'state
state モード_参照 {
  state 対象伝票_入荷伝票 : 入荷日当日
  state 対象伝票_入荷訂正伝票 : 入荷日翌日以降
  state 対象伝票_入荷訂正伝票 {
    state 当日訂正_未
    state 当日訂正_済
  }
}
state モード_新規登録 {
  state ヘッダ入力
  state 明細入力
}
state モード_更新
state モード_訂正登録
state モード_訂正更新
'begin
[*] -down-> モード_新規登録
[*] -down-> モード_参照
'モード_新規登録
ヘッダ入力 -> 明細入力
明細入力 -down-> 対象伝票_入荷伝票 : 登録
'モード_参照
対象伝票_入荷伝票 -down-> モード_更新
当日訂正_未 -down-> モード_訂正登録
当日訂正_済 -down-> モード_訂正更新
対象伝票_入荷伝票 -up-> [*] : 削除
当日訂正_済 -> 当日訂正_未 : 訂正削除
'モード_更新
モード_更新 -> 対象伝票_入荷伝票 : 更新
'モード_訂正登録
モード_訂正登録 -> 当日訂正_済 : 訂正登録
'モード_訂正更新
モード_訂正更新 -> 当日訂正_済 : 訂正更新
'end
@enduml
