@startuml
title
商品入荷登録画面の状態遷移
end title
'state
state 参照モード {
  state 更新可能 : 入荷日当日
  state 訂正可能 : 入荷日翌日以降
  state 訂正可能 {
    state 当日未訂正
    state 当日訂正済
  }
}
state 新規登録モード {
  state ヘッダ入力
  state 明細入力
}
state 更新モード
state 訂正登録モード
state 訂正更新モード
'begin
[*] -down-> 新規登録モード
[*] -down-> 参照モード
'新規登録モード
ヘッダ入力 -> 明細入力
明細入力 -down-> 更新可能 : 登録
'参照モード
更新可能 -down-> 更新モード
当日未訂正 -down-> 訂正登録モード
当日訂正済 -down-> 訂正更新モード
更新可能 -up-> [*] : 削除
当日訂正済 -> 当日未訂正 : 訂正削除
'更新モード
更新モード -> 更新可能 : 更新
'訂正登録モード
訂正登録モード -> 当日訂正済 : 訂正登録
'訂正更新モード
訂正更新モード -> 当日訂正済 : 訂正更新
'end
@enduml
